export class Card {
    CardId: number;
    ScryfallId: string;
    OracleId: string;
    MultiverseId: string;
    MtgoId: number | null;
    MtgoFoilId: number | null;
    ArenaId: number | null;
    TcgplayerId: number | null;
    CardName: string;
    Lang: string;
    ReleasedAt: Date | string;
    Uri: string;
    ScryfallUri: string;
    Layout: string;
    HighresImage: boolean;
    ImageUriPng: string;
    ImageUriBorderCrop: string;
    ImageUriArtCrop: string;
    ImageUriLarge: string;
    ImageUriNormal: string;
    ImageUriSmall: string;
    ManaCost: string;
    Cmc: number;
    TypeLine: string;
    OracleText: string;
    Colors: string;
    ColorIdentity: string;
    ColorIndicator: string;
    LegalityStandard: boolean;
    LegalityFuture: boolean;
    LegalityModern: boolean;
    LegalityLegacy: boolean;
    LegalityPauper: boolean;
    LegalityVintage: boolean;
    LegalityCommander: boolean;
    AvailablePaper: boolean;
    AvailableArena: boolean;
    AvailableMtgo: boolean;
    Reserved: boolean;
    Foil: boolean;
    Nonfoil: boolean;
    Oversized: boolean;
    Promo: boolean;
    Reprint: boolean;
    SetCode: string;
    SetName: string;
    SetUri: string;
    SetSearchUri: string;
    ScryfallSetUri: string;
    RulingsUri: string;
    PrintsSearchUri: string;
    CollectorNumber: string;
    Digital: boolean;
    Rarity: string;
    Watermark: string;
    IllustrationId: string;
    Artist: string;
    BorderColor: string;
    Frame: string;
    FrameEffect: string;
    FullArt: boolean;
    StorySpotlight: boolean;
    RelatedUriTcgplayerDecks: string;
    RelatedUriEdhrec: string;
    RelatedUriMtgtop8: string;
    Power: string;
    Toughness: string;
    FlavorText: string;
    EdhrecRank: number | null;
    Loyalty: string;

    constructor() { }
}
